
title: Carlos César Chávez Padilla
description: Economics PhD Applicant | University of Chicago
theme: jekyll-theme-minimal

author:
  name: Carlos César Chávez Padilla
  email: cesarchavezpadilla@gmail.com

google_scholar: https://scholar.google.com/citations?user=LsVe9yQAAAAJ

markdown: kramdown
