
title: Carlos Chávez
description: Economics PhD Applicant | University of Chicago
theme: jekyll-theme-minimal

author:
  name: Carlos Chávez
  email: cesarchavezpadilla@gmail.com

google_scholar: https://scholar.google.com/citations?user=LsVe9yQAAAAJ

markdown: kramdown
